<?php

/**
 * Class externalHTML
 */
class externalHTML {
    /**
     * @var
     */
    private $content;
    /**
     * @var
     */
    private $url;

    /**
     *
     */
    public function setURL(){

    }

    /**
     * @return mixed
     */
    public function getContent(){
        return $this->content;
    }

    /**
     * TODO URLs aller Bilder sammeln und als Array zurückgeben
     */
    public function getAllImages(){
    }
} 